export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const INIT_LOAD_INVESTIGATORS = 'INIT_LOAD_INVESTIGATORS';
export const LOAD_INVESTIGATORS = 'LOAD_INVESTIGATORS';
export const SUCCESS_LOAD_INVESTIGATORS = 'SUCCESS_LOAD_INVESTIGATORS';
export const ERROR_LOAD_INVESTIGATORS = 'ERROR_LOAD_INVESTIGATORS';
export const INIT_LOGIN = 'INIT_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const INIT_LOADING_PANEL = 'INIT_LOADING_PANEL';
export const FINISH_LOADING_PANEL = 'FINISH_LOADING_PANEL';
//RESUME ACTIONS FORM
export const LOAD_RESUME_INFO = 'LOAD_RESUME_INFO';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_INST = 'CHANGE_INST';
export const CHANGE_DEPTO = 'CHANGE_DEPTO';
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';
export const CHANGE_URL = 'CHANGE_URL';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_INFO = 'CHANGE_INFO';
export const INIT_LOAD_FORM = 'INIT_LOAD_FORM';
export const END_LOAD_FORM = 'END_LOAD_FORM';
//END RESUME ACTIONS
// ADMIN ACTIONS
export const INI_LOAD_ADMIN_INFO = 'INI_LOAD_ADMIN_INFO';
export const LOAD_ADMIN_INFO = 'LOAD_ADMIN_INFO';
export const FINISH_LOAD_ADMIN_INFO = 'FINISH_LOAD_ADMIN_INFO';
export const CHANGE_DEFAULT_PASSWORD = 'CHANGE_DEFAULT_PASSWORD';
export const SAVING_ADMIN_INFO = 'SAVING_ADMIN_INFO';
export const END_SAVING_ADMIN_INFO = 'END_SAVING_ADMIN_INFO';
//END ADMIN ACTIONS