export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const INIT_LOAD_INVESTIGATORS = 'INIT_LOAD_INVESTIGATORS';
export const LOAD_INVESTIGATORS = 'LOAD_INVESTIGATORS';
export const SUCCESS_LOAD_INVESTIGATORS = 'SUCCESS_LOAD_INVESTIGATORS';
export const ERROR_LOAD_INVESTIGATORS = 'ERROR_LOAD_INVESTIGATORS';